version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - LOG_LEVEL=info
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_NAME=my_app
      - DATABASE_PASSWORD=root
    depends_on:
      - postgres

  db:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_app
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql

volumes:
  postgres:
    name: db